$(function(){
    $('#springBtn').click(function(){
        $('#image').removeClass().addClass('spring');
    });
    $('#summerBtn').click(function(){
        $('#image').removeClass().addClass('summer');
    });
    $('#fallBtn').click(function(){
        $('#image').removeClass().addClass('fall');
    });
    $('#winterBtn').click(function(){
        $('#image').removeClass().addClass('winter');
    });
})